repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6  # Latest stable version of pylint
    hooks:
      - id: pylint
        args: ["--disable=C0303, C0415, C0410, C0121, C0114, C0115, C0116, E1101, R0903, C0411, W0611, C0301, R0901, R0902, R0904, C0304, R1705, E0401, C0103, W0613, W1203, R0914, R0901,R0916,R0912"]
        exclude: get-pip.py|manage.py|migrations
