# Generated by Django 5.1.1 on 2024-10-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_ob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
