# Generated by Django 5.1.1 on 2024-11-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_link', '0002_alter_node_created_by_alter_node_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
