# Generated by Django 5.1.1 on 2024-10-17 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "node_link",
            "0002_alter_author_github_token_alter_author_github_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
