# Generated by Django 5.1.1 on 2024-10-15 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "node_link",
            "0002_alter_author_github_token_alter_author_github_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to="node_link.author",
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to="node_link.author",
            ),
        ),
        migrations.AlterField(
            model_name="friends",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to="node_link.author",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to="node_link.author",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to="node_link.author",
            ),
        ),
    ]
