# Generated by Django 5.1.1 on 2024-11-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0003_node_is_active_node_password_node_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_remote",
            field=models.BooleanField(default=False),
        ),
    ]
