# Generated by Django 5.1.1 on 2024-10-17 20:34
# https://docs.djangoproject.com/en/5.1/howto/writing-migrations/#migrations-that-add-unique-fields
from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Post = apps.get_model("node_link", "Post")
    for row in Post.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0003_post_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
