# Generated by Django 5.1.1 on 2024-10-19 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0003_remove_author_local_node_remove_author_user_ptr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="friends",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="friends",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="/static/icons/user_icon.svg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
