# Generated by Django 5.1.1 on 2024-10-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_link', '0003_rename_date_ob_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='date_ob',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='New Post'),
        ),
    ]
