# Generated by Django 5.1.1 on 2024-10-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_link', '0004_rename_date_of_birth_user_date_ob_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
