# Generated by Django 5.1.1 on 2024-11-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0004_node_is_remote"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="raw_password",
            field=models.TextField(blank=True, null=True),
        ),
    ]
