# Generated by Django 5.1.1 on 2024-10-17 20:34


import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0004_add_unique_post_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
