# Generated by Django 5.1.1 on 2024-10-19 00:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "node_link",
            "0004_alter_comment_deleted_at_alter_comment_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
