# Generated by Django 5.1.1 on 2024-10-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0005_auto_20241017_2034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="/static/icons/user_icon.svg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
