# Generated by Django 5.1.1 on 2024-11-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0005_node_raw_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(max_length=50),
        ),
    ]
