# Generated by Django 5.1.1 on 2024-10-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_link', '0006_comment_author_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
