# Generated by Django 5.1.1 on 2024-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0006_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_object_id",
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
