# Generated by Django 5.1.1 on 2024-10-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_link', '0006_alter_user_profile_image'),
        ('node_link', '0007_remove_author_local_node_remove_author_user_ptr_and_more'),
    ]

    operations = [
    ]
