# Generated by Django 5.1.1 on 2024-10-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0007_make_uuid_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_commonmark",
            field=models.BooleanField(default=False),
        ),
    ]
