# Generated by Django 5.1.1 on 2024-10-19 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0008_post_is_commonmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="follower",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("notification_type", models.CharField(max_length=20)),
                (
                    "related_object_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("author_picture_url", models.URLField(blank=True, null=True)),
                ("follow_request_message", models.TextField(blank=True, null=True)),
                ("link_url", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="node_link.authorprofile",
                    ),
                ),
            ],
        ),
    ]
