# Generated by Django 5.1.1 on 2024-10-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_link", "0010_alter_post_visibility"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="friends",
            name="unique_friendship",
        ),
        migrations.RemoveField(
            model_name="friends",
            name="status",
        ),
        migrations.AlterField(
            model_name="follower",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Accepted"), ("D", "Denied")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddConstraint(
            model_name="friends",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user1__lt", models.F("user2"))),
                fields=("user1", "user2"),
                name="unique_friendship",
            ),
        ),
    ]
