# Generated by Django 5.1.1 on 2024-10-30 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authorApp", "0001_initial"),
        ("node_link", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorprofile",
            name="local_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="node_link.node"
            ),
        ),
        migrations.AddField(
            model_name="authorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers_initiated",
                to="authorApp.authorprofile",
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to="authorApp.authorprofile",
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers_received",
                to="authorApp.authorprofile",
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to="authorApp.authorprofile",
            ),
        ),
        migrations.AddField(
            model_name="friends",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to="authorApp.authorprofile",
            ),
        ),
        migrations.AddField(
            model_name="friends",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to="authorApp.authorprofile",
            ),
        ),
        migrations.AddField(
            model_name="friends",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_initiated",
                to="authorApp.authorprofile",
            ),
        ),
        migrations.AddField(
            model_name="friends",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_received",
                to="authorApp.authorprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="follower",
            constraint=models.UniqueConstraint(
                fields=("actor", "object"), name="unique_follower"
            ),
        ),
        migrations.AddConstraint(
            model_name="friends",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2"), name="unique_friendship"
            ),
        ),
    ]
