# Generated by Django 5.1.1 on 2024-11-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorApp", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="friends",
            name="unique_friendship",
        ),
        migrations.RemoveField(
            model_name="friends",
            name="status",
        ),
        migrations.AlterField(
            model_name="follower",
            name="status",
            field=models.CharField(
                choices=[("p", "Pending"), ("a", "Accepted"), ("d", "Denied")],
                default="p",
                max_length=1,
            ),
        ),
        migrations.AddConstraint(
            model_name="friends",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user1__lt", models.F("user2"))),
                fields=("user1", "user2"),
                name="unique_friendship",
            ),
        ),
    ]
