# Generated by Django 5.1.1 on 2024-11-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
