# Generated by Django 5.1.1 on 2024-11-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorApp", "0004_user_is_approved_alter_authorprofile_local_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
