# Generated by Django 5.1.1 on 2024-11-17 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authorApp",
            "0007_alter_user_options_remove_authorprofile_local_node_and_more",
        ),
        ("node_link", "0003_node_is_active_node_password_node_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="local_node",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="node_link.node",
            ),
        ),
    ]
