# Generated by Django 5.1.1 on 2024-11-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorApp", "0009_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorprofile",
            name="fqid",
            field=models.TextField(blank=True, editable=False, unique=True),
        ),
    ]
