# Generated by Django 5.1.1 on 2024-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorApp', '0010_alter_authorprofile_fqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
