# Generated by Django 5.1.1 on 2024-11-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorApp", "0011_alter_authorprofile_last_github_event_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profileImage",
            field=models.URLField(
                blank=True,
                default="https://s3.amazonaws.com/37assets/svn/765-default-avatar.png",
                max_length=255,
                null=True,
            ),
        ),
    ]
