# Generated by Django 5.1.1 on 2024-11-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postApp", "0004_alter_post_uuid_post_unique_uuid_node_combination"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="post",
            name="unique_uuid_node_combination",
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_serial",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="fqid",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="like",
            name="fqid",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="like",
            name="like_serial",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="post",
            name="fqid",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="post",
            name="post_serial",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
