name: Continuous Integration

on:
  push:
    branches: [ "production", "development" ]
  pull_request:
    branches: [ "production", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # this is for things like syntax errors, undefined variables, etc.
    - name: Lint with Pylint
      run: |
        pip install pylint
        pylint socialdistribution/**/*.py    
    ### Uncomment the following lines if you have Django templates and tests (later on)
    # #change the path to the template directory
    # - name: Lint Django Templates with djLint
    #   run: |
    #     pip install djlint
    #     djlint socialdistribution/templates
    # # runs test.py which would have the tests like assertEqual, etc.
    # - name: Run Tests
    #   run: python manage.py test
